source 'https://github.com/CocoaPods/specs.git'

platform :ios, '9.0'
inhibit_all_warnings!

target 'weibo-configure_Example' do
  
  pod 'weibo-configure', :path => '../', :configurations => ['Debug'], :subspecs => [
      'wb-service-configure'
  ]

  target 'weibo-configure_Tests' do
    inherit! :search_paths
    
  end
end
